-- AlterTable
ALTER TABLE `formulario` MODIFY `statusPagamento` ENUM('PENDENTE', 'EM_PROCESSAMENTO', 'APROVADO', 'NAO_APROVADO') NOT NULL DEFAULT 'EM_PROCESSAMENTO';

-- AlterTable
ALTER TABLE `formularioservos` MODIFY `statusPagamento` ENUM('PENDENTE', 'EM_PROCESSAMENTO', 'APROVADO', 'NAO_APROVADO') NOT NULL DEFAULT 'EM_PROCESSAMENTO';
