-- AlterTable
ALTER TABLE `formulario` ADD COLUMN `statusPagamento` ENUM('EM_PROCESSAMENTO', 'APROVADO', 'NAO_APROVADO') NOT NULL DEFAULT 'EM_PROCESSAMENTO';

-- AlterTable
ALTER TABLE `formularioservos` ADD COLUMN `statusPagamento` ENUM('EM_PROCESSAMENTO', 'APROVADO', 'NAO_APROVADO') NOT NULL DEFAULT 'EM_PROCESSAMENTO';
